apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdeployment
spec:
  selector:
    matchLabels:
      app: k8sdeployment
  replicas: 3
  template:
    metadata:
      labels:
        app: k8sdeployment
    spec:
      containers:
        - name: k8sdemo-deployment
          image: k8sdemo-deployment:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
