server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employer/**
        - id: studentModule
          uri: http://localhost:8082/
          predicates:
            - Path=/school/**