apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  template:
    metadata:
      name: myapp-nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx