apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-replica-set
  labels:
    app: my-nginx
    type: front-end
spec:
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container-rs
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: front-end